{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "dnsmasq-k8s.fullname" . }}
  labels:
    {{- include "dnsmasq-k8s.labels" . | nindent 4 }}
  annotations:
    {{ .Values.httpRoute.annotations | toYaml | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "dnsmasq-k8s.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
