apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dnsmasq-k8s-ui.fullname" . }}
  labels:
    {{- include "dnsmasq-k8s-ui.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dnsmasq-k8s-ui.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dnsmasq-k8s-ui.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
