{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dnsmasq-k8s.fullname" . }}-auth
  labels:
    {{- include "dnsmasq-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  users.txt: |
    {{- range $user, $pass := .Values.auth.users }}
    {{ $user }}:{{ $pass }}
    {{- end }}
{{- end }}
