apiVersion: apps/v1
{{- include "dnsmasq-k8s.validateValues" . }}
kind: StatefulSet
metadata:
  name: {{ include "dnsmasq-k8s.fullname" . }}
  labels:
    app: dnsmasq-k8s
spec:
  serviceName: {{ include "dnsmasq-k8s.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dnsmasq-k8s
  template:
    metadata:
      labels:
        app: dnsmasq-k8s
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ include "dnsmasq-k8s.serviceAccountName" . }}
      containers:
        - name: dnsmasq-k8s
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: GIN_MODE
              value: "release"
            - name: DNS_ENABLED
              value: "{{ .Values.dns.enabled }}"
            - name: DHCP_ENABLED
              value: "{{ .Values.dhcp.enabled }}"
            - name: DHCP_LEASE_FILE
              value: "{{ .Values.dhcp.leaseFile }}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WEB_PORT
              value: "{{ .Values.web.port }}"
            {{- if .Values.auth.enabled }}
            - name: BASIC_AUTH_FILE
              value: "/etc/auth/users.txt"
            {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP

            {{- if .Values.dns.enabled }}
            - name: dns
              containerPort: 53
              protocol: UDP
            {{- end }}
            {{- if .Values.dhcp.enabled }}
            - name: dhcp
              containerPort: 67
              protocol: UDP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            {{- if .Values.auth.enabled }}
            - name: auth-volume
              mountPath: "/etc/auth"
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.auth.enabled }}
        - name: auth-volume
          secret:
            secretName: {{ if .Values.auth.existingSecret }}{{ .Values.auth.existingSecret }}{{ else }}{{ include "dnsmasq-k8s.fullname" . }}-auth{{ end }}
        {{- end }}
