apiVersion: apps/v1
{{- include "dnsmasq-k8s-ui.validateValues" . }}
kind: StatefulSet
metadata:
  name: {{ include "dnsmasq-k8s-ui.fullname" . }}
  labels:
    app: dnsmasq-k8s-ui
spec:
  serviceName: {{ include "dnsmasq-k8s-ui.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dnsmasq-k8s-ui
  template:
    metadata:
      labels:
        app: dnsmasq-k8s-ui
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ include "dnsmasq-k8s-ui.serviceAccountName" . }}
      containers:
        - name: dnsmasq-k8s-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: GIN_MODE
              value: "release"
            - name: DNS_ENABLED
              value: "{{ .Values.dns.enabled }}"
            - name: DHCP_ENABLED
              value: "{{ .Values.dhcp.enabled }}"
            - name: DHCP_LEASE_FILE
              value: "{{ .Values.dhcp.leaseFile }}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WEB_PORT
              value: "{{ .Values.web.port }}"
            - name: API_PORT
              value: "{{ .Values.api.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
            - name: api
              containerPort: {{ .Values.api.port }}
              protocol: TCP
            {{- if .Values.dns.enabled }}
            - name: dns
              containerPort: 53
              protocol: UDP
            {{- end }}
            {{- if .Values.dhcp.enabled }}
            - name: dhcp
              containerPort: 67
              protocol: UDP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts: []
      volumes: []
